name: ai_app_jam2024
description: "Google Oyun ve Uygulama Akademisi Yapay Zeka Eklentili uygulama geliştirme jami."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.14.0 # firebase packages
  firebase_auth: ^4.16.0
  firebase_core: ^2.10.0
  google_sign_in: ^6.1.6
  firebase_storage: ^11.6.0
  connectivity: ^3.0.6 #connection internet
  firebase_messaging: ^14.9.2
  introduction_screen: ^3.0.1 #splash ekranları için
  shared_preferences: ^2.0.6
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/background1.png
    - assets/back.png
    - assets/splash1.png
    - assets/splash2.png
    - assets/splash3.png
    - assets/splash4.png
    - assets/logo.png
    - assets/login.png

